# Generated by Django 3.2.14 on 2022-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_newtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ntable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('img1', models.ImageField(upload_to='picts')),
                ('descr', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Newtable',
        ),
    ]
